/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 phone.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/phone.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.078, 0]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Cube005.geometry} material={materials['Screen,glass']} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials.Body} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials.glass} />
        <mesh geometry={nodes.Cube005_3.geometry} material={materials['Metall.paint']} />
        <mesh geometry={nodes.back.geometry} material={materials['Material.007']} position={[-0.052, -0.005, 0]} rotation={[0, -Math.PI / 2, 0]} scale={-1} />
        <group position={[-0.067, 0.003, -0.027]} rotation={[-Math.PI, 0, Math.PI / 2]}>
          <mesh geometry={nodes.Cube004.geometry} material={materials.lense} />
          <mesh geometry={nodes.Cube004_1.geometry} material={materials.Black_rought} />
          <mesh geometry={nodes.Cube004_2.geometry} material={materials['Material.006']} />
        </group>
        <group position={[-0.051, -0.003, -0.017]} rotation={[-Math.PI, 0, Math.PI / 2]}>
          <mesh geometry={nodes.Cube006.geometry} material={materials.lense} />
          <mesh geometry={nodes.Cube006_1.geometry} material={materials.Black_rought} />
          <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.006']} />
        </group>
        <group position={[-0.051, -0.003, -0.006]} rotation={[-Math.PI, 0, Math.PI / 2]}>
          <mesh geometry={nodes.Cube007.geometry} material={materials.lense2} />
          <mesh geometry={nodes.Cube007_1.geometry} material={materials.Black_rought} />
          <mesh geometry={nodes.Cube007_2.geometry} material={materials['Material.006']} />
        </group>
        <group position={[-0.051, -0.003, 0.005]} rotation={[-Math.PI, 0, Math.PI / 2]}>
          <mesh geometry={nodes.Cube008.geometry} material={materials.lense} />
          <mesh geometry={nodes.Cube008_1.geometry} material={materials.Black_rought} />
          <mesh geometry={nodes.Cube008_2.geometry} material={materials['Material.006']} />
        </group>
        <group position={[-0.052, -0.004, 0.013]} rotation={[Math.PI, Math.PI / 2, 0]}>
          <mesh geometry={nodes.Circle001.geometry} material={materials['Diod.glass']} />
          <mesh geometry={nodes.Circle001_1.geometry} material={materials.Diod} />
        </group>
        <group rotation={[-Math.PI, 0, Math.PI / 2]}>
          <mesh geometry={nodes.Plane.geometry} material={materials.frame} />
          <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Plane_2.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Plane_3.geometry} material={materials.steel} />
          <mesh geometry={nodes.Plane_4.geometry} material={materials['Metall.paint']} />
        </group>
        <mesh geometry={nodes.Framecam.geometry} material={materials.Body} position={[-0.052, -0.005, 0]} rotation={[0, -Math.PI / 2, 0]} scale={-1} />
        <mesh geometry={nodes.framein.geometry} material={materials['frame.in']} position={[0, -0.014, 0]} />
        <mesh geometry={nodes.glass.geometry} material={materials.glass} position={[-0.052, -0.004, 0]} rotation={[0, -Math.PI / 2, 0]} scale={-1} />
        <mesh geometry={nodes.glassunder.geometry} material={materials['Black.glass']} position={[-0.052, -0.004, 0]} rotation={[0, -Math.PI / 2, 0]} scale={-1} />
        <mesh geometry={nodes.screenin.geometry} material={materials['Screen.in']} />
        <group position={[-0.052, -0.004, 0.017]} rotation={[-Math.PI, Math.PI / 2, 0]}>
          <mesh geometry={nodes.Plane003.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Plane003_1.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Plane003_2.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Plane003_3.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.Plane003_4.geometry} material={materials['Material.009']} />
        </group>
        <mesh geometry={nodes.speaker.geometry} material={materials['Metall.paint']} position={[-0.074, -0.003, 0]} rotation={[-Math.PI, 0, Math.PI / 2]} />
      </group>
    </group>
  )
}

useGLTF.preload('/phone.glb')
